platform :ios, '13.0'

target 'FirestoreExample' do
  use_frameworks!

  pod 'SDWebImage'

  target 'FirestoreExampleTests' do
    inherit! :search_paths
  end
end

target 'FirestoreSwiftUIExample' do
  use_frameworks!

  pod 'SDWebImageSwiftUI'
end
